### ISSUE TITLE
Deoplete source calling ghc-mod in non-haskell buffer

### ISSUE THREAD

**Issue by Deraen** [eagletmt/neco-ghc#61]
Deoplete source init is calling `necoghc#boot` function (https://github.com/eagletmt/neco-ghc/blob/master/rplugin/python3/deoplete/sources/ghc.py#L22-L23) even when the current buffer is a non Haskell file. This causes error for me as I do not currently have ghc-mod installed. I do not have ghc-mod because I'm not currently working with Haskell, but I would like to keep this plugin installed for future use.

Very quick check to omnicomplete and `boot` code shows that omnifunc is calling `boot` and `boot` is no-op after the first call as it uses a cache var. Maybe it would make sense to move `boot` call in deoplete source to `get_complete_position`?

In neocomplete source, `boot` is called from `on_init` but maybe that is only called for haskell buffers?

```
[deoplete] Traceback (most recent call last):                                                                         
[deoplete]   File "/home/juho/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 57, in com
pletion_begin                                                                                                         
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                        
[deoplete]   File "/home/juho/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 86, in gat
her_candidates                                                                                                        
[deoplete]     self.load_sources()                                                                                    
[deoplete]   File "/home/juho/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 275, in lo
ad_sources                                                                                                            
[deoplete]     self.__sources[name] = source.Source(self.__vim)                                                       
[deoplete]   File "/home/juho/.config/nvim/bundle_haskell/neco-ghc/rplugin/python3/deoplete/sources/ghc.py", line 23, 
in __init__                                                                                                           
[deoplete]     self.vim.call('necoghc#boot')                                                                          
[deoplete]   File "/home/juho/.local/lib/python3.4/site-packages/neovim/api/nvim.py", line 132, in call               
[deoplete]     return self._session.request('vim_call_function', name, args, **kwargs)                                
[deoplete]   File "/home/juho/.local/lib/python3.4/site-packages/neovim/api/common.py", line 230, in request          
[deoplete]     return walk(self._in, self._session.request(name, *args, **kwargs),                                    
[deoplete]   File "/home/juho/.local/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 90, in request  
[deoplete]     raise self.error_wrapper(err)                                                                          
[deoplete] neovim.api.nvim.NvimError: b'vimproc#get_command_name: File "ghc-mod" is not found.'                       
[deoplete] An error has occurred. Please execute :messages command. 
```

**Comment by Shougo** [comment]
Fixed.

**Comment by Deraen** [comment]
Thanks!
